In [1]:
import os
import pandas as pd 
import glob

cwd = os.getcwd()
results_dir = f"{cwd}/results"

In [3]:
htype="mhead"
letters = ["a"]#,"b","c","d","e"]
model_names = ["microsoft/deberta-v3-base","FacebookAI/xlm-roberta-base","dslim/bert-base-NER-uncased"]# ["answerdotai/ModernBERT-base"]
best_params_dct = {l:{mn:[] for mn in model_names} for l in letters}
for l in letters:
    for mn in model_names:
        df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
        el_vals = df["values_0"]
        f1_vals = df["values_1"]
        id_besteval = list(el_vals).index(el_vals.min())
        id_bestf1 = list(f1_vals).index(f1_vals.max())
        if id_besteval == id_bestf1:
            best_params_dct[l][mn].append({
                "eval_loss": df.loc[id_besteval, "values_0"],
                "overall_f1": df.loc[id_besteval, "values_1"],
                "batch_size": df.loc[id_besteval, "params_batch_size"],
                "lr": df.loc[id_besteval, "params_lr"],
                "max_length": df.loc[id_besteval, "params_max_length"],
                "weight_decay": df.loc[id_besteval, "params_weight_decay"]
            })
        else:
            for idx in [id_besteval, id_bestf1]:
                best_params_dct[l][mn].append({
                    "eval_loss": df.loc[idx, "values_0"],
                    "overall_f1": df.loc[idx, "values_1"],
                    "batch_size": df.loc[idx, "params_batch_size"],
                    "lr": df.loc[idx, "params_lr"],
                    "max_length": df.loc[idx, "params_max_length"],
                    "weight_decay": df.loc[idx, "params_weight_decay"]
                })
best_params_dct

{'a': {'microsoft/deberta-v3-base': [{'eval_loss': np.float64(0.3742384007748435),
    'overall_f1': np.float64(0.3006610038669837),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0001362940884457),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0247254115454406)}],
  'FacebookAI/xlm-roberta-base': [{'eval_loss': np.float64(0.3339185785306127),
    'overall_f1': np.float64(0.3382498116418502),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0008944516652745),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0996621754275773)}],
  'dslim/bert-base-NER-uncased': [{'eval_loss': np.float64(0.3357614278793335),
    'overall_f1': np.float64(0.331169811506659),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0004662082074113),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0137793711438788)},
   {'eval_loss': np.float64(0.3471828252077102),
    'overall_f1': np.float64(0.3378772126104323),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0005747326276396),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0247364613384954)}]}}

In [12]:
el_vals = df["values_0"]
f1_vals = df["values_1"]

print(el_vals.min(), f1_vals.max())
print(list(el_vals).index(el_vals.min()), list(f1_vals).index(f1_vals.max()))
df.iloc[5]

0.3422350794076919 0.6062322946175638
5 5

Unnamed: 0                                                        5
number                                                            5
values_0                                                   0.342235
values_1                                                   0.606232
datetime_start                           2026-02-19 23:59:19.612194
datetime_complete                        2026-02-20 00:02:22.288162
duration                                     0 days 00:03:02.675968
params_batch_size                                                 8
params_lr                                                    0.0002
params_max_length                                               256
params_weight_decay                                         0.07455
system_attrs_NSGAIISampler:generation                             0
state                                                      COMPLETE
Name: 5, dtype: object

In [15]:
df.iloc[[5, 6, 9, 11, 16, 21, 24, 26]]

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
5,5,5,0.342235,0.606232,2026-02-19 23:59:19.612194,2026-02-20 00:02:22.288162,0 days 00:03:02.675968,8,0.000200,256,0.074550,0,COMPLETE
6,6,6,0.349024,0.565610,2026-02-20 00:02:22.289119,2026-02-20 00:07:42.885841,0 days 00:05:20.596722,8,0.000066,512,0.013451,0,COMPLETE
9,9,9,0.366925,0.525376,2026-02-20 00:19:19.510936,2026-02-20 00:25:23.063015,0 days 00:06:03.552079,32,0.000185,512,0.089817,0,COMPLETE
11,11,11,0.380471,0.522280,2026-02-20 00:31:15.419041,2026-02-20 00:36:12.225143,0 days 00:04:56.806102,8,0.000050,256,0.079142,0,COMPLETE
16,16,16,0.368861,0.544962,2026-02-20 00:59:05.603885,2026-02-20 01:02:08.525661,0 days 00:03:02.921776,8,0.000106,512,0.098567,0,COMPLETE
21,21,21,0.369268,0.534701,2026-02-20 01:25:26.669672,2026-02-20 01:31:30.828811,0 days 00:06:04.159139,32,0.000275,512,0.075243,0,COMPLETE
24,24,24,0.358257,0.577707,2026-02-20 01:43:41.796942,2026-02-20 01:47:30.457506,0 days 00:03:48.660564,8,0.000101,512,0.097176,0,COMPLETE
26,26,26,0.362504,0.569178,2026-02-20 01:53:34.044074,2026-02-20 01:58:41.943548,0 days 00:05:07.899474,8,0.000095,512,0.072571,0,COMPLETE

In [21]:
l = "a"
htype = "sghead"
mn = "microsoft/deberta-v3-base"
interest="optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/{interest}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[6,9,24,38]]
#df.iloc[[25]]
#df.iloc[[19,35,41]]
#df[df["values_1"]>.48]
#df[df["values_1"]>.35]
df.iloc[[16,48]]
#df.iloc[[19]]

0.3064231226841609 0.6325749949667808
16 48

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
16,16,16,0.306423,0.617580,2026-03-05 14:05:40.554102,2026-03-05 14:17:40.300740,0 days 00:11:59.746638,16,0.00080,512,0.005,0,COMPLETE
48,48,48,0.327864,0.632575,2026-03-05 21:26:12.781010,2026-03-05 21:39:08.222311,0 days 00:12:55.441301,16,0.00085,256,0.035,0,COMPLETE

In [19]:
l = "a"
htype = "sghead"
mn = "FacebookAI/xlm-roberta-base"
interest = "optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/{interest}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[14,16,22,25,44]]
#df.iloc[[4,19]]
#df[df["values_1"]>.6]
#df.iloc[[43,28]]
#df[df["values_1"]>.56]
df.iloc[[32,4]]
#df[df["values_1"]>.40]
#df.iloc[[16]]

0.3024897936143373 0.6397562833206397
32 4

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
32,32,32,0.30249,0.622093,2026-03-06 02:23:49.294667,2026-03-06 02:29:55.146734,0 days 00:06:05.852067,8,0.00052,256,0.020,0,COMPLETE
4,4,4,0.32576,0.639756,2026-03-05 22:24:03.369409,2026-03-05 22:30:59.142445,0 days 00:06:55.773036,16,0.00082,256,0.075,0,COMPLETE

In [ ]:
l = "a"
htype = "mhead"
mn = "dslim/bert-base-NER-uncased"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[4,11,13,15,16,21,31,37,40,41,44]]
#df.iloc[[21,29,34,47,49]]
#df[df["values_1"]>0.6]
#df.iloc[[24,48]]
df[df["values_1"]>0.38]

FileNotFoundError: [Errno 2] No such file or directory: '/home/marwas/polianna_work/results/b/mhead/hyptuning_bert-base-NER-uncased.csv'

In [4]:
l = "a"
htype = "sghead"
mn = "answerdotai/ModernBERT-base"
interest = "optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/{interest}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df[df["values_1"]>0.3]
df.iloc[[8,33]]

0.3049330353373434 0.5867625899280576
8 33

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
8,8,8,0.304933,0.565775,2026-03-08 23:58:38.367915,2026-03-09 00:05:57.335326,0 days 00:07:18.967411,8,0.00073,256,0.075,0,COMPLETE
33,33,33,0.315585,0.586763,2026-03-09 04:44:47.593567,2026-03-09 04:58:07.201149,0 days 00:13:19.607582,8,0.00064,256,0.050,0,COMPLETE