In [1]:
import os
import pandas as pd 
import glob

cwd = os.getcwd()
results_dir = f"{cwd}/results"

In [3]:
htype="mhead"
letters = ["a"]#,"b","c","d","e"]
model_names = ["microsoft/deberta-v3-base","FacebookAI/xlm-roberta-base","dslim/bert-base-NER-uncased"]# ["answerdotai/ModernBERT-base"]
best_params_dct = {l:{mn:[] for mn in model_names} for l in letters}
for l in letters:
    for mn in model_names:
        df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
        el_vals = df["values_0"]
        f1_vals = df["values_1"]
        id_besteval = list(el_vals).index(el_vals.min())
        id_bestf1 = list(f1_vals).index(f1_vals.max())
        if id_besteval == id_bestf1:
            best_params_dct[l][mn].append({
                "eval_loss": df.loc[id_besteval, "values_0"],
                "overall_f1": df.loc[id_besteval, "values_1"],
                "batch_size": df.loc[id_besteval, "params_batch_size"],
                "lr": df.loc[id_besteval, "params_lr"],
                "max_length": df.loc[id_besteval, "params_max_length"],
                "weight_decay": df.loc[id_besteval, "params_weight_decay"]
            })
        else:
            for idx in [id_besteval, id_bestf1]:
                best_params_dct[l][mn].append({
                    "eval_loss": df.loc[idx, "values_0"],
                    "overall_f1": df.loc[idx, "values_1"],
                    "batch_size": df.loc[idx, "params_batch_size"],
                    "lr": df.loc[idx, "params_lr"],
                    "max_length": df.loc[idx, "params_max_length"],
                    "weight_decay": df.loc[idx, "params_weight_decay"]
                })
best_params_dct

{'a': {'microsoft/deberta-v3-base': [{'eval_loss': np.float64(0.3742384007748435),
    'overall_f1': np.float64(0.3006610038669837),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0001362940884457),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0247254115454406)}],
  'FacebookAI/xlm-roberta-base': [{'eval_loss': np.float64(0.3339185785306127),
    'overall_f1': np.float64(0.3382498116418502),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0008944516652745),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0996621754275773)}],
  'dslim/bert-base-NER-uncased': [{'eval_loss': np.float64(0.3357614278793335),
    'overall_f1': np.float64(0.331169811506659),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0004662082074113),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0137793711438788)},
   {'eval_loss': np.float64(0.3471828252077102),
    'overall_f1': np.float64(0.3378772126104323),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0005747326276396),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0247364613384954)}]}}

In [12]:
el_vals = df["values_0"]
f1_vals = df["values_1"]

print(el_vals.min(), f1_vals.max())
print(list(el_vals).index(el_vals.min()), list(f1_vals).index(f1_vals.max()))
df.iloc[5]

0.3422350794076919 0.6062322946175638
5 5

Unnamed: 0                                                        5
number                                                            5
values_0                                                   0.342235
values_1                                                   0.606232
datetime_start                           2026-02-19 23:59:19.612194
datetime_complete                        2026-02-20 00:02:22.288162
duration                                     0 days 00:03:02.675968
params_batch_size                                                 8
params_lr                                                    0.0002
params_max_length                                               256
params_weight_decay                                         0.07455
system_attrs_NSGAIISampler:generation                             0
state                                                      COMPLETE
Name: 5, dtype: object

In [15]:
df.iloc[[5, 6, 9, 11, 16, 21, 24, 26]]

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
5,5,5,0.342235,0.606232,2026-02-19 23:59:19.612194,2026-02-20 00:02:22.288162,0 days 00:03:02.675968,8,0.000200,256,0.074550,0,COMPLETE
6,6,6,0.349024,0.565610,2026-02-20 00:02:22.289119,2026-02-20 00:07:42.885841,0 days 00:05:20.596722,8,0.000066,512,0.013451,0,COMPLETE
9,9,9,0.366925,0.525376,2026-02-20 00:19:19.510936,2026-02-20 00:25:23.063015,0 days 00:06:03.552079,32,0.000185,512,0.089817,0,COMPLETE
11,11,11,0.380471,0.522280,2026-02-20 00:31:15.419041,2026-02-20 00:36:12.225143,0 days 00:04:56.806102,8,0.000050,256,0.079142,0,COMPLETE
16,16,16,0.368861,0.544962,2026-02-20 00:59:05.603885,2026-02-20 01:02:08.525661,0 days 00:03:02.921776,8,0.000106,512,0.098567,0,COMPLETE
21,21,21,0.369268,0.534701,2026-02-20 01:25:26.669672,2026-02-20 01:31:30.828811,0 days 00:06:04.159139,32,0.000275,512,0.075243,0,COMPLETE
24,24,24,0.358257,0.577707,2026-02-20 01:43:41.796942,2026-02-20 01:47:30.457506,0 days 00:03:48.660564,8,0.000101,512,0.097176,0,COMPLETE
26,26,26,0.362504,0.569178,2026-02-20 01:53:34.044074,2026-02-20 01:58:41.943548,0 days 00:05:07.899474,8,0.000095,512,0.072571,0,COMPLETE

In [17]:
l = "e"
htype = "mhead"
mn = "microsoft/deberta-v3-base"
interest="optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/{interest}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[6,9,24,38]]
#df.iloc[[25]]
#df.iloc[[19,35,41]]
#df[df["values_1"]>.48]
#df[df["values_1"]>.35]
df.iloc[[10,5]]
#df.iloc[[39]]

0.9000625207143671 0.39095287262564
10 5

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
10,10,10,0.900063,0.383163,2026-03-18 01:12:30.829511,2026-03-18 01:30:57.012281,0 days 00:18:26.182770,8,0.00079,512,0.03,0,COMPLETE
5,5,5,0.959512,0.390953,2026-03-17 22:54:27.772775,2026-03-17 23:26:54.004815,0 days 00:32:26.232040,8,0.00029,512,0.07,0,COMPLETE

In [19]:
l = "e"
htype = "mhead"
mn = "FacebookAI/xlm-roberta-base"
interest = "optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/{interest}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[14,16,22,25,44]]
#df.iloc[[4,19]]
#df[df["values_1"]>.6]
#df.iloc[[43,28]]
#df[df["values_1"]>.56]
df.iloc[[44,7]]
#df[df["values_1"]>.40]
#df.iloc[[16]]

0.860902281069174 0.4297637180846318
44 7

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
44,44,44,0.860902,0.409211,2026-03-19 12:32:54.973457,2026-03-19 12:44:09.982098,0 days 00:11:15.008641,8,0.00071,256,0.035,0,COMPLETE
7,7,7,0.875643,0.429764,2026-03-18 22:55:10.759917,2026-03-18 23:10:39.563373,0 days 00:15:28.803456,8,0.00055,256,0.010,0,COMPLETE

In [19]:
l = "e"
htype = "mhead"
mn = "dslim/bert-base-NER-uncased"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[4,11,13,15,16,21,31,37,40,41,44]]
#df.iloc[[21,29,34,47,49]]
#df[df["values_1"]>0.6]
df.iloc[[1,44]]
#df.iloc[[17]]
#df[df["values_1"]>0.38]

0.9381166696548462 0.4033242453834958
1 44

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
1,1,1,0.938117,0.380101,2026-03-12 22:07:44.203937,2026-03-12 22:12:41.999222,0 days 00:04:57.795285,8,0.00036,512,0.09,0,COMPLETE
44,44,44,0.947268,0.403324,2026-03-13 01:31:29.615353,2026-03-13 01:36:41.319474,0 days 00:05:11.704121,8,0.00037,512,0.00,0,COMPLETE

In [3]:
l = "e"
htype = "sghead"
mn = "answerdotai/ModernBERT-base"
interest = "optuna"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df[df["values_1"]>0.3]
#df.iloc[[27,35]]
df.iloc[[13]]

0.6735014816125234 0.4005663048607834
13 13

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
13,13,13,0.673501,0.400566,2026-03-13 12:53:41.865100,2026-03-13 13:16:53.370124,0 days 00:23:11.505024,8,0.00034,512,0.02,0,COMPLETE

# Synthesis

In [23]:
fname = f"{cwd}/inputs/hyperparameters.xlsx"
hyp_df = pd.read_excel(fname)
hyp_df

,letter,model,htype,batch_size,lr,max_length,weight_decay
0,a,microsoft/deberta-v3-base,sghead,16,0.00080,512,0.005
1,a,microsoft/deberta-v3-base,mhead,16,0.00062,512,0.080
2,a,FacebookAI/xlm-roberta-base,sghead,8,0.00052,256,0.020
3,a,FacebookAI/xlm-roberta-base,mhead,8,0.00074,512,0.050
4,a,dslim/bert-base-NER-uncased,sghead,8,0.00041,256,0.095
5,a,dslim/bert-base-NER-uncased,mhead,8,0.00051,256,0.000
6,a,answerdotai/ModernBERT-base,sghead,8,0.00064,256,0.050
7,a,answerdotai/ModernBERT-base,mhead,16,0.00075,768,0.085
8,b,microsoft/deberta-v3-base,sghead,8,0.00071,512,0.040
9,b,microsoft/deberta-v3-base,mhead,8,0.00063,256,0.065
10,b,FacebookAI/xlm-roberta-base,sghead,16,0.00083,512,0.075
11,b,FacebookAI/xlm-roberta-base,mhead,8,0.00082,256,0.015
12,b,dslim/bert-base-NER-uncased,sghead,8,0.00085,256,0.070
13,b,dslim/bert-base-NER-uncased,mhead,8,0.00042,256,0.100
14,b,answerdotai/ModernBERT-base,sghead,8,0.00057,256,0.090
15,b,answerdotai/ModernBERT-base,mhead,8,0.00077,768,0.100
16,c,microsoft/deberta-v3-base,sghead,8,0.00070,256,0.030
17,c,microsoft/deberta-v3-base,mhead,8,0.00088,512,0.055
18,c,FacebookAI/xlm-roberta-base,sghead,8,0.00049,256,0.055
19,c,FacebookAI/xlm-roberta-base,mhead,8,0.00031,256,0.050
20,c,dslim/bert-base-NER-uncased,sghead,32,0.00074,256,0.080
21,c,dslim/bert-base-NER-uncased,mhead,8,0.00047,512,0.095
22,c,answerdotai/ModernBERT-base,sghead,16,0.00090,256,0.040
23,c,answerdotai/ModernBERT-base,mhead,8,0.00082,1024,0.020
24,d,microsoft/deberta-v3-base,sghead,16,0.00065,512,0.095
25,d,microsoft/deberta-v3-base,mhead,8,0.00055,512,0.025
26,d,FacebookAI/xlm-roberta-base,sghead,32,0.00046,256,0.070
27,d,FacebookAI/xlm-roberta-base,mhead,32,0.00066,256,0.015
28,d,dslim/bert-base-NER-uncased,sghead,8,0.00047,512,0.005
29,d,dslim/bert-base-NER-uncased,mhead,8,0.00044,256,0.070
30,d,answerdotai/ModernBERT-base,sghead,16,0.00081,256,0.010
31,d,answerdotai/ModernBERT-base,mhead,8,0.00060,768,0.080
32,e,microsoft/deberta-v3-base,sghead,8,0.00059,512,0.100
33,e,microsoft/deberta-v3-base,mhead,8,0.00079,512,0.030
34,e,FacebookAI/xlm-roberta-base,sghead,16,0.00082,256,0.075
35,e,FacebookAI/xlm-roberta-base,mhead,8,0.00055,256,0.010
36,e,dslim/bert-base-NER-uncased,sghead,8,0.00069,512,0.000
37,e,dslim/bert-base-NER-uncased,mhead,8,0.00037,512,0.000
38,e,answerdotai/ModernBERT-base,sghead,8,0.00034,512,0.020
39,e,answerdotai/ModernBERT-base,mhead,8,0.00087,768,0.020

In [24]:
new_json = {}
for htype in ["sghead","mhead"]:
    new_json[htype]={}
    for letter in ["a","b","c","d","e"]:
        new_json[htype][letter]= {model:{} for model in ["microsoft/deberta-v3-base","FacebookAI/xlm-roberta-base","dslim/bert-base-NER-uncased","answerdotai/ModernBERT-base"]}
new_json

{'sghead': {'a': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'b': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'c': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'd': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'e': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}}},
 'mhead': {'a': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'b': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'c': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'd': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}},
  'e': {'microsoft/deberta-v3-base': {},
   'FacebookAI/xlm-roberta-base': {},
   'dslim/bert-base-NER-uncased': {},
   'answerdotai/ModernBERT-base': {}}}}

In [26]:
for idx in hyp_df.index:
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["num_epochs"] = 30
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["batch_size"] = int(hyp_df.loc[idx,"batch_size"])
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["lr"] = float(hyp_df.loc[idx,"lr"])
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["max_length"] = int(hyp_df.loc[idx,"max_length"])
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["weight_decay"] = float(hyp_df.loc[idx,"weight_decay"])
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["num_warmup_steps"] = 0
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["patience"] = 5
    new_json[hyp_df.loc[idx,"htype"]][hyp_df.loc[idx,"letter"]][hyp_df.loc[idx,"model"]]["dropout"] = 0.1
new_json

{'sghead': {'a': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.0008,
    'max_length': 512,
    'weight_decay': 0.005,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00052,
    'max_length': 256,
    'weight_decay': 0.02,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00041,
    'max_length': 256,
    'weight_decay': 0.095,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00064,
    'max_length': 256,
    'weight_decay': 0.05,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'b': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00071,
    'max_length': 512,
    'weight_decay': 0.04,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00083,
    'max_length': 512,
    'weight_decay': 0.075,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00085,
    'max_length': 256,
    'weight_decay': 0.07,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00057,
    'max_length': 256,
    'weight_decay': 0.09,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'c': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.0007,
    'max_length': 256,
    'weight_decay': 0.03,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00049,
    'max_length': 256,
    'weight_decay': 0.055,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 32,
    'lr': 0.00074,
    'max_length': 256,
    'weight_decay': 0.08,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.0009,
    'max_length': 256,
    'weight_decay': 0.04,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'd': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00065,
    'max_length': 512,
    'weight_decay': 0.095,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 32,
    'lr': 0.00046,
    'max_length': 256,
    'weight_decay': 0.07,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00047,
    'max_length': 512,
    'weight_decay': 0.005,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00081,
    'max_length': 256,
    'weight_decay': 0.01,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'e': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00059,
    'max_length': 512,
    'weight_decay': 0.1,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00082,
    'max_length': 256,
    'weight_decay': 0.075,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00069,
    'max_length': 512,
    'weight_decay': 0.0,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00034,
    'max_length': 512,
    'weight_decay': 0.02,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}}},
 'mhead': {'a': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00062,
    'max_length': 512,
    'weight_decay': 0.08,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00074,
    'max_length': 512,
    'weight_decay': 0.05,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00051,
    'max_length': 256,
    'weight_decay': 0.0,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 16,
    'lr': 0.00075,
    'max_length': 768,
    'weight_decay': 0.085,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'b': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00063,
    'max_length': 256,
    'weight_decay': 0.065,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00082,
    'max_length': 256,
    'weight_decay': 0.015,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00042,
    'max_length': 256,
    'weight_decay': 0.1,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00077,
    'max_length': 768,
    'weight_decay': 0.1,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'c': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00088,
    'max_length': 512,
    'weight_decay': 0.055,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00031,
    'max_length': 256,
    'weight_decay': 0.05,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00047,
    'max_length': 512,
    'weight_decay': 0.095,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00082,
    'max_length': 1024,
    'weight_decay': 0.02,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'd': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00055,
    'max_length': 512,
    'weight_decay': 0.025,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 32,
    'lr': 0.00066,
    'max_length': 256,
    'weight_decay': 0.015,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00044,
    'max_length': 256,
    'weight_decay': 0.07,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.0006,
    'max_length': 768,
    'weight_decay': 0.08,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}},
  'e': {'microsoft/deberta-v3-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00079,
    'max_length': 512,
    'weight_decay': 0.03,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'FacebookAI/xlm-roberta-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00055,
    'max_length': 256,
    'weight_decay': 0.01,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'dslim/bert-base-NER-uncased': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00037,
    'max_length': 512,
    'weight_decay': 0.0,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1},
   'answerdotai/ModernBERT-base': {'num_epochs': 30,
    'batch_size': 8,
    'lr': 0.00087,
    'max_length': 768,
    'weight_decay': 0.02,
    'num_warmup_steps': 0,
    'patience': 5,
    'dropout': 0.1}}}}