In [2]:
import os
import pandas as pd 
import glob

cwd = os.getcwd()
results_dir = f"{cwd}/results"

In [3]:
htype="mhead"
letters = ["a"]#,"b","c","d","e"]
model_names = ["microsoft/deberta-v3-base","FacebookAI/xlm-roberta-base","dslim/bert-base-NER-uncased"]# ["answerdotai/ModernBERT-base"]
best_params_dct = {l:{mn:[] for mn in model_names} for l in letters}
for l in letters:
    for mn in model_names:
        df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
        el_vals = df["values_0"]
        f1_vals = df["values_1"]
        id_besteval = list(el_vals).index(el_vals.min())
        id_bestf1 = list(f1_vals).index(f1_vals.max())
        if id_besteval == id_bestf1:
            best_params_dct[l][mn].append({
                "eval_loss": df.loc[id_besteval, "values_0"],
                "overall_f1": df.loc[id_besteval, "values_1"],
                "batch_size": df.loc[id_besteval, "params_batch_size"],
                "lr": df.loc[id_besteval, "params_lr"],
                "max_length": df.loc[id_besteval, "params_max_length"],
                "weight_decay": df.loc[id_besteval, "params_weight_decay"]
            })
        else:
            for idx in [id_besteval, id_bestf1]:
                best_params_dct[l][mn].append({
                    "eval_loss": df.loc[idx, "values_0"],
                    "overall_f1": df.loc[idx, "values_1"],
                    "batch_size": df.loc[idx, "params_batch_size"],
                    "lr": df.loc[idx, "params_lr"],
                    "max_length": df.loc[idx, "params_max_length"],
                    "weight_decay": df.loc[idx, "params_weight_decay"]
                })
best_params_dct

{'a': {'microsoft/deberta-v3-base': [{'eval_loss': np.float64(0.3742384007748435),
    'overall_f1': np.float64(0.3006610038669837),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0001362940884457),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0247254115454406)}],
  'FacebookAI/xlm-roberta-base': [{'eval_loss': np.float64(0.3339185785306127),
    'overall_f1': np.float64(0.3382498116418502),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0008944516652745),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0996621754275773)}],
  'dslim/bert-base-NER-uncased': [{'eval_loss': np.float64(0.3357614278793335),
    'overall_f1': np.float64(0.331169811506659),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0004662082074113),
    'max_length': np.int64(512),
    'weight_decay': np.float64(0.0137793711438788)},
   {'eval_loss': np.float64(0.3471828252077102),
    'overall_f1': np.float64(0.3378772126104323),
    'batch_size': np.int64(8),
    'lr': np.float64(0.0005747326276396),
    'max_length': np.int64(256),
    'weight_decay': np.float64(0.0247364613384954)}]}}

In [12]:
el_vals = df["values_0"]
f1_vals = df["values_1"]

print(el_vals.min(), f1_vals.max())
print(list(el_vals).index(el_vals.min()), list(f1_vals).index(f1_vals.max()))
df.iloc[5]

0.3422350794076919 0.6062322946175638
5 5

Unnamed: 0                                                        5
number                                                            5
values_0                                                   0.342235
values_1                                                   0.606232
datetime_start                           2026-02-19 23:59:19.612194
datetime_complete                        2026-02-20 00:02:22.288162
duration                                     0 days 00:03:02.675968
params_batch_size                                                 8
params_lr                                                    0.0002
params_max_length                                               256
params_weight_decay                                         0.07455
system_attrs_NSGAIISampler:generation                             0
state                                                      COMPLETE
Name: 5, dtype: object

In [15]:
df.iloc[[5, 6, 9, 11, 16, 21, 24, 26]]

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
5,5,5,0.342235,0.606232,2026-02-19 23:59:19.612194,2026-02-20 00:02:22.288162,0 days 00:03:02.675968,8,0.000200,256,0.074550,0,COMPLETE
6,6,6,0.349024,0.565610,2026-02-20 00:02:22.289119,2026-02-20 00:07:42.885841,0 days 00:05:20.596722,8,0.000066,512,0.013451,0,COMPLETE
9,9,9,0.366925,0.525376,2026-02-20 00:19:19.510936,2026-02-20 00:25:23.063015,0 days 00:06:03.552079,32,0.000185,512,0.089817,0,COMPLETE
11,11,11,0.380471,0.522280,2026-02-20 00:31:15.419041,2026-02-20 00:36:12.225143,0 days 00:04:56.806102,8,0.000050,256,0.079142,0,COMPLETE
16,16,16,0.368861,0.544962,2026-02-20 00:59:05.603885,2026-02-20 01:02:08.525661,0 days 00:03:02.921776,8,0.000106,512,0.098567,0,COMPLETE
21,21,21,0.369268,0.534701,2026-02-20 01:25:26.669672,2026-02-20 01:31:30.828811,0 days 00:06:04.159139,32,0.000275,512,0.075243,0,COMPLETE
24,24,24,0.358257,0.577707,2026-02-20 01:43:41.796942,2026-02-20 01:47:30.457506,0 days 00:03:48.660564,8,0.000101,512,0.097176,0,COMPLETE
26,26,26,0.362504,0.569178,2026-02-20 01:53:34.044074,2026-02-20 01:58:41.943548,0 days 00:05:07.899474,8,0.000095,512,0.072571,0,COMPLETE

In [4]:
l = "a"
htype = "mhead"
mn = "microsoft/deberta-v3-base"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[6,9,24,38]]
#df.iloc[[25]]
#df.iloc[[19,35,41]]
#df[df["values_1"]>.48]
#df[df["values_1"]>.35]
#df.iloc[[15,32]]
df.iloc[[19]]

0.3487952815161811 0.2962634737311111
19 19

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
19,19,19,0.348795,0.296263,2026-03-07 15:31:33.602218,2026-03-07 15:43:15.794225,0 days 00:11:42.192007,16,0.00062,512,0.08,0,COMPLETE

In [7]:
l = "a"
htype = "mhead"
mn = "FacebookAI/xlm-roberta-base"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[14,16,22,25,44]]
#df.iloc[[4,19]]
#df[df["values_1"]>.6]
#df.iloc[[43,28]]
#df[df["values_1"]>.56]
#df.iloc[[49,28]]
#df[df["values_1"]>.40]
df.iloc[[16]]

0.3329667864661467 0.3445918498370838
16 16

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
16,16,16,0.332967,0.344592,2026-03-07 20:36:31.021494,2026-03-07 20:42:23.217644,0 days 00:05:52.196150,8,0.00074,512,0.05,0,COMPLETE

In [ ]:
l = "b"
htype = "mhead"
mn = "dslim/bert-base-NER-uncased"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df.iloc[[11,19,22,23,33,34,45]]
#df.iloc[[4,11,13,15,16,21,31,37,40,41,44]]
#df.iloc[[21,29,34,47,49]]
#df[df["values_1"]>0.6]
#df.iloc[[24,48]]
df[df["values_1"]>0.38]

0.9105843603610992 0.3983749032231861
8 37

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
8,8,8,0.910584,0.396579,2026-02-28 11:39:35.109399,2026-02-28 11:50:59.075831,0 days 00:11:23.966432,8,0.000603,256,0.082578,0,COMPLETE
22,22,22,0.952327,0.382193,2026-02-28 16:01:26.362750,2026-02-28 16:19:52.807567,0 days 00:18:26.444817,8,0.000281,512,0.059271,0,COMPLETE
36,36,36,0.963379,0.386009,2026-02-28 20:01:56.003393,2026-02-28 20:12:10.603260,0 days 00:10:14.599867,8,0.000538,256,0.084829,0,COMPLETE
37,37,37,0.941521,0.398375,2026-02-28 20:12:10.604933,2026-02-28 20:23:37.256984,0 days 00:11:26.652051,8,0.000554,256,0.088785,0,COMPLETE
46,46,46,0.944741,0.387073,2026-02-28 22:27:43.333840,2026-02-28 22:38:35.177831,0 days 00:10:51.843991,8,0.000585,512,0.087057,0,COMPLETE

In [28]:
l = "d"
htype = "mhead"
mn = "answerdotai/ModernBERT-base"
df = pd.read_csv(f"{cwd}/results/{l}/{htype}/hyptuning_{mn.split('/')[-1]}.csv")
el_vals = df["values_0"]
f1_vals = df["values_1"]
print(el_vals.min(), f1_vals.max())
id_besteval = list(el_vals).index(el_vals.min())
id_bestf1 = list(f1_vals).index(f1_vals.max())
print(id_besteval,id_bestf1)

df
#df[df["values_1"]>0.3]
df.iloc[[27]]

0.5840041518211365 0.5274692106283165
27 27

,Unnamed: 0,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_max_length,params_weight_decay,system_attrs_NSGAIISampler:generation,state
27,27,27,0.584004,0.527469,2026-03-06 19:03:25.319739,2026-03-06 19:15:38.326358,0 days 00:12:13.006619,8,0.0006,768,0.08,0,COMPLETE